# Generated by Django 4.2.5 on 2023-10-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=50)),
                ('lead_type', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('processing', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'laeds_master',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Type', models.CharField(max_length=30)),
                ('durations', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'task_master',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_Name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('products_Dealing', models.CharField(max_length=50)),
                ('quotation', models.IntegerField()),
                ('negotiation', models.IntegerField()),
                ('deal_Status', models.CharField(max_length=10)),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerData.leads')),
            ],
            options={
                'db_table': 'delas_master',
            },
        ),
    ]
